# syntax=docker/dockerfile:1

FROM node:14 AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build-storybook 

FROM nginx AS runner
COPY --from=builder /app/storybook-static /usr/share/nginx/html
