@baseUrl=https://bankeesit.feib.com.tw/v2isg
# @baseUrl=http://10.48.167.154:8080/service/v2isg
#@baseUrl=http://10.48.161.147:8082
#@baseUrl=http://10.48.167.154:8082

@custId=S174343754

### MBGW GNR_LOGIN
### 2022-04-15 TEST OK.
# @name login
POST {{baseUrl}}/mbgw/v2.0/gnr-login
content-type: application/json

{
  "txnId": "RC_{{$guid}}",
  "custId": "{{custId}}",
  "udid": "48c3d54d-bab3-471a-9778-2c98a157c3f8",
  "channelCode": "HHB_A",
  "appVersion": "1.0.15",
  "txSeq": "20210506172346",
  "username": "Ws/7XBQqbExNVvdP9FXhwnom9XA79F+BAqZppd4lv6BRUTKAfqCHH/i7BcxkIGaHj2pbmg6Jt+fB/CSI787tjwG0paFZ2rBEcj/Rhw5QvAeSkrDNwTARzkC+5oOkBoxekXVqDQuMCo5ufayaB+kNyMiTlf18dCUx0STXpNlTUsM6EIuZ8/446BhN7tlPd0xI5zj2rUtioeMd8oxs7bKLr815w9hwg1/soKKPxecU+STI20MzKRJujRdzUajvRgD8kyOeRF6GuzJ8O5BPMpy4lX08Am20FN0vQ7/ehFt7SAIN/aiVDwYecrTccJBE0E7DXDygHENTmSJzQTEEDtsQMJ1Crnq9mac7euxNlw7vVEodTa2WUImQ/dzivsvvUKk0arypHU2IMednq+Ida9iQM6EKlpZhb/5QLpuYThZ8FgjEIFxcVLNisdkCd/hBTO05I2BYG2E11Q8JEC7PgnvzHUygvx3mEeSzzzIeDjNbeRmHCYhLRA3Ri++EmXpO8kXJtihUoBYRMOb9K5qr9RFMEFYzrI3W+EwOhnsdRNbV/kyPC+GQYp+InJdrCj8m7lbYqaKD0LXG7jYkRv24Bk6//SCBUSGKBgWytb8MAsX+M7TK6WhW6dqNJ/dTiyrsfI9WjrwqD09Z/lLLt8ZkDaplclRfq4DKvDUSPQJ19COYUK9qSf29ECT+/A==",
  "password": "PdoYaBX6MWFeIu1WiD2xyHdcFLwkH5lhNY/DqrSsuo3KAraGYJQdzwIqSMs/kMQW/KUO+/8Pm4rCfnTzKtEPifz1WEcRiXzdB07/0OoQwSwQKKY3UpJvcdw1reP2VXwknEMrKnnVGFaH4RDyWWb7bIl0VpDuFNXu9KLFeQ1mnHFqJgxCjLL5VPz4Riu+y51zvYPqJE45rHTHc+krV9Kq2zpgnLTPojrxXVfjZecH33vT7soM9nYr6mUZ5duy2wZvoZq9nWELcFsl5uyFYw4Anv8xom83/Z3Nq6UYTve3n/sf4ekXdXlbkdx+cmpHnUjHWN24MVeXKhluFFKWEeXMegEzfwoT/gCn2HjkTLAF6tWdQYrPAy+It87OvzB9gKOED+/OMfJ6GzEidHKd8NZTnj7PcFfRnow1f5OorirFt0HruMqIz954Q+FCInewZmEDuH7GyoTKraeYqOO6BZSRvOY4f79HFSnlafcBZDMLTbSsnNPBd60+p6mgvdPIKX6WLdzp/ZMDFlvnb62X6MAMFpu/SlyxkfTfXYZLZPBOKsBsNLLbHK6ydaRcGeQZbQOvE+/1hAgtLQ084zvq7FEnkzKET1y1eZVrw2aedrAi+5yPgZZBUUV4WOgaLUHDKcgc89oGNTeLuWzEwTeCXrXtRCXI9d7NVEdKpMaZqWlahcNqSf29ECT+/A=="
}

###===========
### ISG Token.
###===========
@isgToken = {{login.response.body.data}}

# IB.Q_ACCT 轉出帳號查詢
POST {{baseUrl}}/mbgw/v1.0/q-acct
content-type: application/json

{
  "isgToken": "{{isgToken}}",
  "txnId": "RC_{{$guid}}",
  "custId": "{{custId}}",
  "acctStyle": "O",
  "qstyleO": "2",
  "isNtd": "Y"
}