export const mockFavoriteList = {
  favoriteList: [
    {
      id: '1',
      group: 'account',
      groupName: '帳戶服務',
      blocks: [
        {
          id: 'account1',
          label: '帳戶總覽',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'account2',
          label: '台幣活存',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'account3',
          label: '外幣活存',
          selected: false,
          disabled: true,
          selectedOrder: null,
        },
        {
          id: 'account4',
          label: '證券交割帳戶',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'account5',
          label: '台幣定存',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'account6',
          label: '存錢計畫',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'account7',
          label: '社群帳本',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'account9',
          label: '匯出存摺',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
      ],
    },
    {
      id: '2',
      group: 'apply',
      groupName: '申請',
      blocks: [
        {
          id: 'apply1',
          label: '申請台幣活存',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'apply2',
          label: '申請外幣活存',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'apply3',
          label: '申請證券交割帳戶',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'apply4',
          label: '申請信用卡',
          selected: true,
          disabled: false,
          selectedOrder: 4,
        },
        {
          id: 'apply5',
          label: '申請貸款',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
      ],
    },
    {
      id: '3',
      group: 'transaction',
      groupName: '轉帳提款',
      blocks: [
        {
          id: 'transaction1',
          label: '台幣轉帳',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'transaction2',
          label: '外幣轉帳',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'transaction3',
          label: 'QR CODE轉帳',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'transaction4',
          label: '無卡提款',
          selected: true,
          disabled: false,
          selectedOrder: 2,
        },
        {
          id: 'transaction5',
          label: '變更無卡提款密碼',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'transaction6',
          label: '境外快速匯',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'transaction7',
          label: '常用帳號管理',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'transaction8',
          label: '約定帳號管理',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
      ],
    },
    {
      id: '4',
      group: 'invest',
      groupName: '投資理財',
      blocks: [
        {
          id: 'invest1',
          label: '換匯',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'invest2',
          label: '匯率',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'invest3',
          label: '金融百貨',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
      ],
    },
    {
      id: '5',
      group: 'creditCard',
      groupName: '信用卡',
      blocks: [
        {
          id: 'creditCard1',
          label: '即時消費明細',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'creditCard2',
          label: '帳單明細',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'creditCard3',
          label: '繳費',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'creditCard4',
          label: '額度臨調',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'creditCard5',
          label: '自動扣繳申請/查詢',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
      ],
    },
    {
      id: '6',
      group: 'loan',
      groupName: '貸款',
      blocks: [
        {
          id: 'loan1',
          label: '我的貸款',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'loan2',
          label: '應繳查詢',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
      ],
    },
    {
      id: '7',
      group: 'helper',
      groupName: '金融助手',
      blocks: [
        {
          id: 'helper1',
          label: '個人化設定',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'helper3',
          label: '手機號碼收款設定',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'helper4',
          label: '數存會員升級(立即驗)',
          selected: true,
          disabled: false,
          selectedOrder: 3,
        },
        {
          id: 'helper5',
          label: '視訊約定帳號設定',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'helper6',
          label: '預約轉帳查詢',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'helper7',
          label: '訊息通知設定',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'helper8',
          label: '他行存款自動存入設定',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'helper9',
          label: '常見問題',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'helper10',
          label: '金融卡啟用',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'helper11',
          label: '金融卡掛失補發',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
      ],
    },
    {
      id: '8',
      group: 'social',
      groupName: '社群圈',
      blocks: [
        {
          id: 'social1',
          label: '社群圈',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'social2',
          label: '好友查詢',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
        {
          id: 'social3',
          label: '社群圈分潤',
          selected: false,
          disabled: false,
          selectedOrder: null,
        },
      ],
    },
  ],
};
